title: ФТ-302

markdown: kramdown
theme: minima

header_pages:
  - index.md
  - news.md
  - calendar.md
  - about.md
  - _.md
  - courses/terver/index.md
  - courses/index.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: default