title: ФТ-302

markdown: kramdown
theme: minima

header_pages:
  - courses/assembler/index.md
  - courses/web/index.md
  - courses/combalg/index.md
  - courses/graphs/index.md
  - courses/alg/index.md
  - courses/terver/index.md
  - courses/funcan/index.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: default