title: ФТ-302

markdown: kramdown
theme: minima

header_pages:
  - index.md
  - news.md
  - calendar.md
  - about.md
  - a.md
  - courses/web/index.md
  - courses/assembler/index.md
  - courses/terver/index.md
  - courses/index.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: default