title: ФТ-302

markdown: kramdown
theme: minima

header_pages:
  - news.md
  - calendar.md
  - tasks/index.md
  - about.md
  - texts/terver/index.md
  - texts/index.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: default